openapi: 3.0.1
info:
  title: Документация по API сервиса product
  contact:
    email: it4it@otpbank.ru
  version: 0.1.0
tags:
  - name: Tag
    description: Операции по работе со справочником тегов
  - name: Product
    description: Операции по работе с продуктом
paths:
  /v1/tags/{id}:
    get:
      parameters:
        - name: id
          in: path
          schema:
            type: string
          description: Идентификатор тега
          required: true
      tags:
        - Tag
      summary: Получение тега по идентификатору
      operationId: getTagById
      responses:
        200:
          description: Найденный тег
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        404:
          description: Тег не найден
    delete:
      parameters:
        - name: id
          in: path
          schema:
            type: string
          description: Идентификатор тега
          required: true
      tags:
        - Tag
      summary: Удаление тега
      operationId: deleteTag
      responses:
        200:
          description: Тег удален
        404:
          description: Тег не найден
    put:
      parameters:
        - name: id
          in: path
          schema:
            type: string
          description: Идентификатор тега
          required: true
      tags:
        - Tag
      summary: Обновление тега и его параметров
      operationId: updateTag
      requestBody:
        description: Новые данные тега для обновления
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      responses:
        200:
          description: Обновленный тег
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        404:
          description: Тег не найден
      x-codegen-request-body-name: tag
  /v1/tags:
    get:
      tags:
        - Tag
      summary: Получение тегов
      operationId: findTags
      responses:
        200:
          description: Найденные теги
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    post:
      tags:
        - Tag
      summary: Создание тега
      operationId: addTag
      requestBody:
        description: Параметры тега
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
      responses:
        200:
          description: Созданный тег
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        405:
          description: Ошибки валидации
      x-codegen-request-body-name: tag
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          description: Идентификатор тега
          type: string
          format: int64
        name:
          description: Название тега
          type: string
        description:
          description: Описание тега
          type: string