openapi: 3.0.1
info:
  title: Документация по API
  description: Пример описания API для микросервисов
  contact:
    email: it4it@otpbank.ru
  version: 0.1.0
tags:
  - name: TemplateDocument
    description: Операции по работе с шаблонами документов
  - name: Samples
    description: Примеры методов
paths:
  /v1/templates:
    get:
      tags:
        - Sample
      operationId: hello
      responses:
        200:
          description: hello
          content:
            application/json:
              schema:
                type: string
  /v1/templates/find:
    get:
      tags:
        - Sample
      operationId: find
      responses:
        200:
          description: find
          content:
            application/json:
              schema:
                type: string
  /v1/templates/documents/{id}:
    get:
      parameters:
        - name: id
          in: path
          schema:
            type: string
          description: Идентификатор шаблона
          required: true
      tags:
        - TemplateDocument
      summary: Получение шаблона по идентификатору
      operationId: getTemplateDocumentById
      responses:
        200:
          description: Найденный шаблон
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateDocument'
        404:
          description: Шаблон не найден
    put:
      parameters:
        - name: id
          in: path
          schema:
            type: string
          description: Идентификатор шаблона
          required: true
      tags:
        - TemplateDocument
      summary: Обновление шаблона и его параметров
      operationId: updateTemplateDocument
      requestBody:
        description: Новые данные шаблона для обновления
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateDocument'
        required: true
      responses:
        200:
          description: Обновленный шаблон
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateDocument'
        404:
          description: Шаблон не найден
      x-codegen-request-body-name: template
  /v1/templates/documents:
    get:
      tags:
        - TemplateDocument
      summary: Получение шаблона по идентификатору
      operationId: findTemplateDocuments
      responses:
        200:
          description: Найденные шаблоны
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/TemplateDocument'
    post:
      tags:
        - TemplateDocument
      summary: Создание шаблона
      operationId: addTemplateDocument
      requestBody:
        description: Параметры шаблона
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateDocument'
        required: true
      responses:
        200:
          description: Созданный шаблон
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateDocument'
        405:
          description: Ошибки валидации
      x-codegen-request-body-name: template
components:
  schemas:
    TemplateDocument:
      type: object
      properties:
        id:
          description: Идентификатор шаблона
          type: string
        name:
          description: Название шаблона
          type: string
        version:
          description: Версия шаблона
          type: integer
          format: int32
        creationDate:
          description: Дата создания шаблона
          type: string
          format: date-time
        tags:
          description: Список шаблонов
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: Статус шаблона
          enum:
            - CREATED
            - ACTIVE
            - ARCHIVED
    Tag:
      type: object
      properties:
        id:
          description: Идентификатор тега
          type: string
          format: int64
        name:
          description: Название тега
          type: string
